#This is to pass variables from job1 to job2
name: passing variable from job1 to job2
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_out1: ${{ steps.set_output.outputs.message }}
      my_out2: ${{ steps.set_output.outputs.result }}
    steps:
      - id: set_output
        run: |
          message="hello this from job1"
          result="$((2+1))"
          echo "message=$message" >> $GITHUB_OUTPUT
          echo "result=$result" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: print_the variables
        run: |
          echo "message from job1: ${{needs.job1.outputs.my_out1}}"
          echo "result from job1: ${{needs.job1.outputs.my_out2}}"
